import type { WordSeed } from "../types";

function w(english: string, azeri: string, category: string, icon: string): WordSeed {
  return { english, azeri, category, icon, synonyms: [] };
}

/** Additional A1 everyday vocabulary */
export const A1_EXTRA_SEEDS: WordSeed[] = [
  w("hello", "salam", "everyday", "👋"),
  w("goodbye", "sağ ol", "everyday", "👋"),
  w("please", "xahiş edirəm", "everyday", "🙏"),
  w("thank you", "təşəkkür edirəm", "everyday", "🙏"),
  w("sorry", "bağışlayın", "everyday", "😔"),
  w("yes", "bəli", "everyday", "✅"),
  w("no", "xeyr", "everyday", "❌"),
  w("name", "ad", "everyday", "📛"),
  w("friend", "dost", "everyday", "🤝"),
  w("family", "ailə", "family", "👨‍👩‍👧"),
  w("mother", "ana", "family", "👩"),
  w("father", "ata", "family", "👨"),
  w("sister", "bacı", "family", "👧"),
  w("brother", "qardaş", "family", "👦"),
  w("child", "uşaq", "family", "🧒"),
  w("baby", "körpə", "family", "👶"),
  w("husband", "ər", "family", "👨"),
  w("wife", "arvad", "family", "👩"),
  w("one", "bir", "numbers", "1️⃣"),
  w("two", "iki", "numbers", "2️⃣"),
  w("three", "üç", "numbers", "3️⃣"),
  w("four", "dörd", "numbers", "4️⃣"),
  w("five", "beş", "numbers", "5️⃣"),
  w("ten", "on", "numbers", "🔟"),
  w("twenty", "iyirmi", "numbers", "2️⃣0️⃣"),
  w("hundred", "yüz", "numbers", "💯"),
  w("red", "qırmızı", "colors", "🔴"),
  w("blue", "mavi", "colors", "🔵"),
  w("green", "yaşıl", "colors", "🟢"),
  w("yellow", "sarı", "colors", "🟡"),
  w("black", "qara", "colors", "⚫"),
  w("white", "ağ", "colors", "⚪"),
  w("today", "bu gün", "time", "📅"),
  w("tomorrow", "sabah", "time", "📅"),
  w("yesterday", "dünən", "time", "📅"),
  w("morning", "səhər", "time", "🌅"),
  w("evening", "axşam", "time", "🌆"),
  w("night", "gecə", "time", "🌙"),
  w("hour", "saat", "time", "⏰"),
  w("minute", "dəqiqə", "time", "⏱️"),
  w("week", "həftə", "time", "📆"),
  w("month", "ay", "time", "📆"),
  w("year", "il", "time", "📆"),
  w("park", "park", "places", "🌳"),
  w("street", "küçə", "places", "🛣️"),
  w("city", "şəhər", "places", "🏙️"),
  w("country", "ölkə", "places", "🌍"),
  w("shop", "mağaza", "places", "🛍️"),
  w("hospital", "xəstəxana", "places", "🏥"),
  w("airport", "aeroport", "basic travel", "✈️"),
  w("ticket", "bilet", "basic travel", "🎫"),
  w("passport", "pasport", "basic travel", "🛂"),
  w("hotel", "otel", "basic travel", "🏨"),
  w("map", "xəritə", "basic travel", "🗺️"),
  w("eat", "yemək", "basic verbs", "🍽️"),
  w("drink", "içmək", "basic verbs", "🥤"),
  w("go", "getmək", "basic verbs", "🚶"),
  w("come", "gəlmək", "basic verbs", "👉"),
  w("see", "görmək", "basic verbs", "👀"),
  w("hear", "eşitmək", "basic verbs", "👂"),
  w("speak", "danışmaq", "basic verbs", "🗣️"),
  w("read", "oxumaq", "basic verbs", "📖"),
  w("write", "yazmaq", "basic verbs", "✍️"),
  w("work", "işləmək", "basic verbs", "💼"),
  w("sleep", "yatmaq", "basic verbs", "😴"),
  w("open", "açmaq", "basic verbs", "🔓"),
  w("close", "bağlamaq", "basic verbs", "🔒"),
  w("big", "böyük", "basic adjectives", "⬆️"),
  w("small", "kiçik", "basic adjectives", "⬇️"),
  w("good", "yaxşı", "basic adjectives", "👍"),
  w("bad", "pis", "basic adjectives", "👎"),
  w("new", "yeni", "basic adjectives", "✨"),
  w("old", "köhnə", "basic adjectives", "📦"),
  w("hot", "isti", "basic adjectives", "🔥"),
  w("cold", "soyuq", "basic adjectives", "❄️"),
  w("happy", "xoşbəxt", "basic adjectives", "😊"),
  w("sad", "kədərli", "basic adjectives", "😢"),
  w("fast", "sürətli", "basic adjectives", "⚡"),
  w("slow", "yavaş", "basic adjectives", "🐢"),
  w("computer", "kompüter", "simple technology", "💻"),
  w("internet", "internet", "simple technology", "🌐"),
  w("email", "e-poçt", "simple technology", "📧"),
  w("password", "parol", "simple technology", "🔑"),
  w("screen", "ekran", "simple technology", "🖥️"),
  w("mouse", "siçan", "simple technology", "🖱️"),
  w("keyboard", "klaviatura", "simple technology", "⌨️"),
  w("wifi", "Wi-Fi", "simple technology", "📶"),
  w("app", "tətbiq", "simple technology", "📱"),
  w("meat", "ət", "food", "🥩"),
  w("fruit", "meyvə", "food", "🍎"),
  w("vegetable", "tərəvəz", "food", "🥕"),
  w("butter", "kərə yağı", "food", "🧈"),
  w("juice", "şirə", "food", "🧃"),
  w("breakfast", "səhər yeməyi", "food", "🍳"),
  w("lunch", "nahar", "food", "🍱"),
  w("dinner", "şam yeməyi", "food", "🍽️"),
];
