import type { WordSeed } from "../types";

function w(
  english: string,
  azeri: string,
  category: string,
  icon: string,
  synonyms: string[] = [],
  exampleEn?: string,
  exampleAz?: string,
  hint?: string,
): WordSeed {
  return { english, azeri, category, icon, synonyms, exampleEn, exampleAz, hint };
}

/** B2: backend, .NET, APIs, travel fluency — curated seeds */
export const B2_SEEDS: WordSeed[] = [
  w(
    "authentication",
    "autentifikasiya / istifadəçinin kimliyinin yoxlanması",
    "authentication",
    "🔐",
    ["identity verification", "login verification"],
    "The API requires authentication before returning user data.",
    "API istifadəçi məlumatlarını qaytarmadan əvvəl autentifikasiya tələb edir.",
    "Used when the system checks who the user is.",
  ),
  w("authorization", "avtorizasiya / icazənin yoxlanması", "authorization", "🛡️", ["access control"]),
  w("architecture", "arxitektura", "architecture", "🏗️", ["system design"]),
  w("dependency injection", "asılılığın injeksiyası", "backend development", "💉", ["DI"]),
  w("middleware", "middleware / aralıq proqram təbəqəsi", "backend development", "🔗"),
  w("endpoint", "endpoint / API nöqtəsi", "API development", "📍", ["API route"]),
  w("payload", "payload / sorğu və ya cavab məzmunu", "API development", "📦", ["request body"]),
  w("request header", "sorğu başlığı", "API development", "📨"),
  w("response body", "cavab gövdəsi", "API development", "📄"),
  w("access token", "giriş tokeni", "authentication", "🎫"),
  w("refresh token", "yeniləmə tokeni", "authentication", "🔄"),
  w("migration", "miqrasiya / verilənlər bazası köçürməsi", "database performance", "🗄️"),
  w("stored procedure", "saxlanılan prosedur", "SQL", "⚙️"),
  w("query performance", "sorğu performansı", "database performance", "⚡"),
  w("deadlock", "deadlock / qarşılıqlı bloklama", "database performance", "🔒"),
  w("transaction", "tranzaksiya", "database performance", "💳"),
  w("repository pattern", "repository pattern / repozitoriya nümunəsi", "backend development", "📚"),
  w("background service", "fon xidməti", "backend development", "⏳"),
  w("deployment", "deploy / yerləşdirmə", "deployment", "🚀"),
  w("monitoring", "monitorinq", "monitoring", "📊"),
  w("log entry", "log qeydi", "logging", "📝"),
  w("exception handling", "istisna emalı", "debugging", "⚠️"),
  w("validation rule", "validasiya qaydası", "backend development", "✅"),
  w("rate limit", "sürət limiti", "API development", "🚦"),
  w("retry policy", "təkrar cəhd siyasəti", "backend development", "🔁"),
  w("message queue", "mesaj növbəsi", "backend development", "📬"),
  w("integration", "inteqrasiya", "backend development", "🔌"),
  w("production issue", "prodaksiya problemi", "deployment", "🔥"),
  w("rollback", "rollback / geri qaytarma", "deployment", "↩️"),
  w("hotfix", "hotfix / təcili düzəliş", "deployment", "🩹"),
  w("code review", "kod baxışı", "code review", "👀"),
  w("pull request", "pull request / PR", "code review", "🔀"),
  w("environment variable", "mühit dəyişəni", "deployment", "🌐"),
  w("configuration", "konfiqurasiya", "deployment", "⚙️"),
  w("connection string", "qoşulma sətri", "database performance", "🔗"),
  w("caching", "keşləmə", "backend development", "💾"),
  w("serialization", "serializasiya", "backend development", "📦"),
  w("deserialization", "deserializasiya", "backend development", "📭"),
  w("dependency", "asılılıq", "backend development", "📎"),
  w("package", "paket", "dotnet", "📦"),
  w("build pipeline", "build pipeline / qurma boru xətti", "deployment", "🏭"),
  w("release", "buraxılış", "deployment", "🏷️"),
  w("incident", "insident / hadisə", "deployment", "🚨"),
  w("root cause", "kök səbəb", "debugging", "🌱"),
  w("boarding pass", "biniş kartı", "travel fluency", "🎫"),
  w("delayed flight", "gecikmiş uçuş", "travel fluency", "✈️"),
  w("baggage claim", "baqajın götürülməsi", "travel fluency", "🧳"),
  w("reservation", "rezervasiya", "travel fluency", "📅"),
  w("check-in desk", "qeydiyyat masası", "travel fluency", "🛎️"),
  w("local customs", "yerli adət-ənənələr", "travel fluency", "🌍"),
  w("recommendation", "tövsiyə", "social fluency", "👍"),
  w("conversation starter", "söhbətə başlama ifadəsi", "social fluency", "💬"),
  w("misunderstanding", "anlaşılmazlıq", "social fluency", "❓"),
  w("appointment", "görüş / randevu", "professional communication", "📆"),
  w("nearby", "yaxınlıqda", "travel fluency", "📍"),
  w("affordable", "münasib qiymətli", "travel fluency", "💰"),
  w("crowded", "sıxıq / kalabalıq", "travel fluency", "👥"),
  w("comfortable", "rahat", "travel fluency", "🛋️"),
  w("available", "mövcuddur", "professional communication", "✅"),
  w("convenient", "rahattır / əlverişlidir", "travel fluency", "👌"),
  w("scalability", "miqyaslanma", "architecture", "📈"),
  w("microservice", "mikroservis", "architecture", "🧩"),
  w("load balancer", "yükləmə balanslayıcısı", "architecture", "⚖️"),
  w("service contract", "xidmət müqaviləsi", "API development", "📜"),
  w("idempotency", "idempotentlik", "API development", "🔁"),
  w("webhook", "webhook", "API development", "🪝"),
  w("API gateway", "API gateway", "API development", "🚪"),
  w("OpenAPI", "OpenAPI spesifikasiyası", "technical documentation", "📘"),
  w("Swagger", "Swagger sənədləşməsi", "technical documentation", "📗"),
  w("DTO", "DTO / data transfer object", "backend development", "📋"),
  w("entity framework", "Entity Framework", "dotnet", "🗃️"),
  w("LINQ", "LINQ sorğusu", "dotnet", "🔍"),
  w("async await", "async/await", "CSharp", "⏱️"),
  w("garbage collection", "zibil yığımı", "CSharp", "🗑️"),
  w("nullable reference", "nullable reference", "CSharp", "❔"),
  w("record type", "record tipi", "CSharp", "📇"),
  w("interface segregation", "interfeys segregasiyası", "architecture", "🧱"),
  w("single responsibility", "tək məsuliyyət prinsipi", "architecture", "1️⃣"),
  w("unit of work", "unit of work", "backend development", "📦"),
  w("CQRS", "CQRS", "architecture", "🔀"),
  w("event sourcing", "event sourcing", "architecture", "📡"),
  w("distributed cache", "paylanmış keş", "caching", "🌐"),
  w("Redis", "Redis", "caching", "🔴"),
  w("connection pool", "qoşulma hovuzu", "database performance", "🏊"),
  w("index scan", "indeks skanı", "SQL", "🔎"),
  w("execution plan", "icra planı", "SQL", "🗺️"),
  w("foreign key", "xarici açar", "SQL", "🔑"),
  w("primary key", "əsas açar", "SQL", "🗝️"),
  w("normalization", "normalizasiya", "SQL", "📐"),
  w("denormalization", "denormalizasiya", "SQL", "📊"),
  w("sharding", "şarding", "database performance", "🧱"),
  w("replication lag", "replikasiya gecikməsi", "database performance", "⏳"),
  w("failover", "failover", "cloud basics", "🔄"),
  w("high availability", "yüksək əlçatanlıq", "cloud basics", "🟢"),
  w("container image", "konteyner şəkli", "deployment", "🐳"),
  w("Kubernetes", "Kubernetes", "cloud basics", "☸️"),
  w("health check", "sağlamlıq yoxlaması", "monitoring", "❤️"),
  w("structured logging", "strukturlaşdırılmış loglama", "logging", "📋"),
  w("correlation id", "korrelyasiya ID-si", "logging", "🔗"),
  w("distributed tracing", "paylanmış izləmə", "monitoring", "🛤️"),
  w("metrics dashboard", "metrik paneli", "monitoring", "📊"),
  w("alert threshold", "xəbərdarlıq həddi", "monitoring", "🚨"),
  w("on-call rotation", "növbəli növbə", "deployment", "📞"),
  w("postmortem", "postmortem / hadisəsonrası analiz", "deployment", "📑"),
  w("SLA", "SLA / xidmət səviyyəsi müqaviləsi", "professional communication", "📃"),
  w("technical debt", "texniki borc", "code review", "💳"),
  w("refactoring", "refaktorinq", "code review", "🔧"),
  w("breaking change", "uyğunsuz dəyişiklik", "code review", "💥"),
  w("semver", "semver / semantik versiyalaşdırma", "deployment", "🏷️"),
  w("feature flag", "funksiya bayrağı", "deployment", "🚩"),
  w("blue-green deployment", "blue-green deployment", "deployment", "🔵"),
  w("canary release", "canary buraxılışı", "deployment", "🐤"),
  w("infrastructure as code", "kod kimi infrastruktur", "cloud basics", "🏗️"),
  w("secrets manager", "sirrlər meneceri", "cloud basics", "🔐"),
  w("TLS certificate", "TLS sertifikatı", "authentication", "📜"),
  w("OAuth", "OAuth", "authentication", "🔑"),
  w("JWT", "JWT token", "authentication", "🎫"),
  w("role-based access", "rol əsaslı giriş", "authorization", "👤"),
  w("policy-based authorization", "siyasət əsaslı avtorizasiya", "authorization", "📋"),
  w("multi-factor authentication", "çox faktorlu autentifikasiya", "authentication", "🔢"),
  w("password hashing", "parol hashləmə", "authentication", "🔒"),
  w("salt", "salt / duz dəyəri", "authentication", "🧂"),
  w("penetration test", "penetrasyon testi", "authentication", "🎯"),
  w("SQL injection", "SQL injection", "SQL", "💉"),
  w("input sanitization", "giriş təmizləməsi", "backend development", "🧼"),
  w("cross-site scripting", "cross-site scripting", "backend development", "⚠️"),
  w("CORS", "CORS", "API development", "🌐"),
  w("content negotiation", "məzmun razılaşdırması", "API development", "🤝"),
  w("pagination", "səhifələmə", "API development", "📄"),
  w("filtering", "filtrasiya", "API development", "🔍"),
  w("sorting", "sıralama", "API development", "↕️"),
  w("bulk endpoint", "toplu endpoint", "API development", "📦"),
  w("versioning strategy", "versiyalaşdırma strategiyası", "API development", "🔢"),
  w("backward compatibility", "geriyə uyğunluq", "API development", "↩️"),
  w("contract testing", "müqavilə testi", "backend development", "🧪"),
  w("integration test", "inteqrasiya testi", "backend development", "🔗"),
  w("unit test", "vahid test", "backend development", "🧪"),
  w("mock object", "mock obyekt", "backend development", "🎭"),
  w("test coverage", "test əhatəsi", "code review", "📊"),
  w("CI pipeline", "CI pipeline", "build pipeline", "🔄"),
  w("artifact", "artifact / qurma nəticəsi", "build pipeline", "📦"),
  w("NuGet feed", "NuGet feed", "dotnet", "📦"),
  w("solution file", "solution faylı", "dotnet", "📁"),
  w("project reference", "layihə istinadı", "dotnet", "🔗"),
  w("target framework", "hədəf framework", "dotnet", "🎯"),
  w("nullable warning", "nullable xəbərdarlığı", "CSharp", "⚠️"),
  w("compiler error", "kompilyator xətası", "debugging", "❌"),
  w("stack trace", "stack trace", "debugging", "📚"),
  w("breakpoint", "breakpoint / fasilə nöqtəsi", "debugging", "⏸️"),
  w("watch window", "watch pəncərəsi", "debugging", "👁️"),
  w("memory leak", "yaddaş sızması", "debugging", "💧"),
  w("race condition", "yarış vəziyyəti", "debugging", "🏁"),
  w("thread safety", "thread təhlükəsizliyi", "backend development", "🧵"),
  w("concurrency", "paralellik", "backend development", "🔀"),
  w("throughput", "keçirim", "database performance", "📈"),
  w("latency", "gecikmə", "database performance", "⏱️"),
  w("bottleneck", "darboğaz", "database performance", "🍾"),
  w("profiling", "profilinq", "debugging", "📊"),
  w("benchmark", "benchmark", "database performance", "🏁"),
  w("technical specification", "texniki spesifikasiya", "technical documentation", "📄"),
  w("runbook", "runbook / əməliyyat kitabçası", "technical documentation", "📘"),
  w("architecture decision record", "arxitektura qərar qeydi", "technical documentation", "📝"),
  w("stakeholder update", "maraqdar tərəf yeniləməsi", "professional communication", "📣"),
  w("sprint planning", "sprint planlaşdırması", "meetings", "📅"),
  w("daily standup", "gündəlik standap", "meetings", "🧍"),
  w("retrospective", "retrospektiv", "meetings", "🔙"),
  w("action item", "hərəkət maddəsi", "meetings", "✅"),
  w("blocker", "bloklayıcı", "meetings", "🚧"),
  w("scope creep", "scope genişlənməsi", "meetings", "📈"),
  w("estimate", "qiymətləndirmə", "meetings", "🧮"),
  w("technical interview", "texniki müsahibə", "interviews", "🎤"),
  w("system design interview", "sistem dizaynı müsahibəsi", "interviews", "🏗️"),
  w("whiteboard session", "ağ lövhə sessiyası", "interviews", "🖊️"),
  w("behavioral question", "davranış sualı", "interviews", "🗣️"),
  w("salary negotiation", "maaş danışıqları", "interviews", "💼"),
  w("layover", "qısa gözləmə / tranzit", "travel fluency", "🛫"),
  w("customs declaration", "gömrük bəyanatı", "travel fluency", "📋"),
  w("travel insurance", "səyahət sığortası", "travel fluency", "🛡️"),
  w("room upgrade", "otaq yüksəltməsi", "travel fluency", "⬆️"),
  w("late checkout", "gec çıxış", "travel fluency", "🕐"),
  w("dietary restriction", "qida məhdudiyyəti", "travel fluency", "🥗"),
  w("allergy", "allergiya", "travel fluency", "🤧"),
  w("receipt", "qəbz", "travel fluency", "🧾"),
  w("refund policy", "geri ödəmə siyasəti", "travel fluency", "💸"),
  w("lost luggage", "itmiş baqaj", "travel fluency", "😟"),
  w("gate change", "qapı dəyişikliyi", "travel fluency", "🚪"),
  w("seat assignment", "oturacaq təyini", "travel fluency", "💺"),
  w("immigration officer", "miqrasiya məmuru", "travel fluency", "🛂"),
  w("visa requirement", "viza tələbi", "travel fluency", "📄"),
  w("currency exchange", "valyuta mübadiləsi", "travel fluency", "💱"),
  w("pickpocket", "oğru / cibgir", "travel fluency", "⚠️"),
  w("politely decline", "nəzakətlə imtina etmək", "social fluency", "🙏"),
  w("small talk", "kiçik söhbət", "social fluency", "☕"),
  w("follow up", "izləmə / geri əlaqə", "professional communication", "📧"),
  w("clarify expectations", "gözləntiləri aydınlaşdırmaq", "professional communication", "💡"),
  w("push back", "etiraz etmək / müqavimət göstərmək", "professional communication", "✋"),
  w("align on priorities", "prioritetlərdə razılaşmaq", "professional communication", "🎯"),
  w("escalate", "yuxarı səviyyəyə qaldırmaq", "professional communication", "⬆️"),
  w("delegate", "tapşırıq vermək", "professional communication", "👥"),
  w("ownership", "məsuliyyət / sahiblik", "professional communication", "🧭"),
  w("consensus", "konsensus", "meetings", "🤝"),
  w("trade-off", "kompromis / mübadilə", "architecture", "⚖️"),
  w("non-functional requirement", "funksional olmayan tələb", "architecture", "📋"),
  w("observability", "müşahidəolunma", "monitoring", "👁️"),
  w("circuit breaker", "circuit breaker", "backend development", "⚡"),
  w("bulkhead pattern", "bulkhead pattern", "architecture", "🚢"),
  w("saga pattern", "saga pattern", "architecture", "📖"),
  w("outbox pattern", "outbox pattern", "backend development", "📤"),
  w("poison message", "zəhərli mesaj", "message queue", "☠️"),
  w("dead letter queue", "dead letter queue", "message queue", "📭"),
  w("consumer group", "consumer qrupu", "message queue", "👥"),
  w("partition key", "partisiya açarı", "message queue", "🔑"),
  w("eventual consistency", "yekun tutarlılıq", "database performance", "⏳"),
  w("strong consistency", "güclü tutarlılıq", "database performance", "💪"),
  w("optimistic concurrency", "optimist paralellik", "database performance", "😊"),
  w("pessimistic lock", "pessimist kilid", "database performance", "🔒"),
  w("migration script", "miqrasiya skripti", "SQL", "📜"),
  w("seed data", "seed məlumat", "SQL", "🌱"),
  w("backup restore", "ehtiyat nüsxəsi bərpası", "database performance", "💾"),
  w("point-in-time recovery", "müəyyən anda bərpa", "database performance", "⏰"),
  w("compliance audit", "uyğunluq auditi", "professional communication", "📋"),
  w("data retention", "məlumat saxlanması", "database performance", "🗄️"),
  w("PII", "şəxsi məlumat (PII)", "professional communication", "🔒"),
  w("GDPR", "GDPR", "professional communication", "🇪🇺"),
  w("threat model", "təhdid modeli", "authentication", "🎯"),
  w("least privilege", "minimum səlahiyyət", "authorization", "🔐"),
  w("defense in depth", "dərinlikdə müdafiə", "authentication", "🛡️"),
  w("zero trust", "sıfır etibar", "authentication", "0️⃣"),
  w("service mesh", "service mesh", "cloud basics", "🕸️"),
  w("serverless function", "serverless funksiya", "cloud basics", "☁️"),
  w("cold start", "soyuq başlanğıc", "cloud basics", "❄️"),
  w("auto scaling", "avtomatik miqyaslanma", "cloud basics", "📈"),
  w("cost optimization", "xərc optimallaşdırması", "cloud basics", "💰"),
  w("technical roadmap", "texniki yol xəritəsi", "professional communication", "🗺️"),
  w("proof of concept", "sübut konsepti", "backend development", "🧪"),
  w("minimum viable product", "minimum həyat qabil məhsul", "backend development", "🚀"),
  w("legacy system", "köhnə sistem", "architecture", "🏛️"),
  w("strangler pattern", "strangler pattern", "architecture", "🐍"),
  w("API deprecation", "API ləğvi", "API development", "🗑️"),
  w("sunset date", "ləğv tarixi", "API development", "🌅"),
  w("changelog", "dəyişiklik jurnalı", "technical documentation", "📋"),
  w("release notes", "buraxılış qeydləri", "technical documentation", "📝"),
  w("knowledge transfer", "bilik ötürülməsi", "professional communication", "🎓"),
  w("pair programming", "cütlük proqramlaşdırma", "code review", "👥"),
  w("rubber duck debugging", "rubber duck debugging", "debugging", "🦆"),
  w("repro steps", "təkrarlama addımları", "debugging", "🔁"),
  w("severity level", "ciddilik səviyyəsi", "deployment", "📶"),
  w("workaround", "müvəqqəti həll", "debugging", "🩹"),
  w("permanent fix", "daimi düzəliş", "debugging", "✅"),
  w("regression", "reqressiya", "debugging", "📉"),
  w("smoke test", "smoke test", "deployment", "💨"),
  w("staging environment", "staging mühiti", "deployment", "🎭"),
  w("production environment", "prodaksiya mühiti", "deployment", "🏭"),
  w("configuration drift", "konfiqurasiya sürüşməsi", "deployment", "📉"),
  w("immutable infrastructure", "dəyişməz infrastruktur", "cloud basics", "🧱"),
  w("infrastructure drift", "infrastruktur sürüşməsi", "cloud basics", "📉"),
  w("run locally", "lokal işə salmaq", "debugging", "💻"),
  w("attach debugger", "debugger qoşmaq", "debugging", "🐛"),
  w("conditional breakpoint", "şərtli breakpoint", "debugging", "⏸️"),
  w("log level", "log səviyyəsi", "logging", "📊"),
  w("verbose logging", "ətraflı loglama", "logging", "📢"),
  w("PII masking", "PII maskalama", "logging", "🎭"),
  w("audit trail", "audit izi", "logging", "👣"),
  w("business metric", "biznes metriki", "monitoring", "📈"),
  w("error budget", "xəta büdcəsi", "monitoring", "💰"),
  w("mean time to recovery", "ortalama bərpa müddəti", "monitoring", "⏱️"),
  w("capacity planning", "tutum planlaşdırması", "architecture", "📊"),
  w("disaster recovery", "fəlakət bərpası", "cloud basics", "🆘"),
  w("RTO", "RTO / bərpa vaxt hədəfi", "cloud basics", "⏰"),
  w("RPO", "RPO / məlumat itkisi hədəfi", "cloud basics", "💾"),
];
