import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { CEFRLevel } from "../src/features/words/config/levels";
import type { WordItem } from "../src/features/words/types";

type SeedWord = {
  english: string;
  azeri: string;
  category: string;
  icon: string;
  synonyms: string[];
  acceptedAnswers?: string[];
  exampleEn?: string;
  exampleAz?: string;
};

function s(
  english: string,
  azeri: string,
  category: string,
  icon: string,
  synonyms: string[] = [],
  acceptedAnswers: string[] = [],
): SeedWord {
  return { english, azeri, category, icon, synonyms, acceptedAnswers };
}

function unique(values: string[]): string[] {
  return Array.from(new Set(values.map((value) => value.trim()).filter(Boolean)));
}

function makeExampleEn(english: string): string {
  return `Please say "${english}" clearly in English.`;
}

function makeExampleAz(azeri: string): string {
  return `"${azeri}" sözünü ingiliscə aydın deyin.`;
}

function hintFor(english: string): string {
  const visible = english
    .split(" ")
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${"_".repeat(Math.max(part.length - 1, 1))}`)
    .join(" ");
  return `${visible} (${english.length} letters including spaces)`;
}

function build(level: CEFRLevel, seeds: SeedWord[]): WordItem[] {
  return seeds.map((seed, index) => ({
    id: `${level.toLowerCase()}_${String(index + 1).padStart(4, "0")}`,
    level,
    english: seed.english,
    azeri: seed.azeri,
    acceptedAnswers: unique([seed.english, ...(seed.acceptedAnswers ?? [])]),
    synonyms: seed.synonyms,
    category: seed.category,
    icon: seed.icon,
    exampleEn: seed.exampleEn ?? makeExampleEn(seed.english),
    exampleAz: seed.exampleAz ?? makeExampleAz(seed.azeri),
    hint: hintFor(seed.english),
  }));
}

const a1 = build("A1", [
  s("apple", "alma", "food", "🍎", ["fruit"], ["an apple"]),
  s("banana", "banan", "food", "🍌", ["fruit"], ["a banana"]),
  s("orange", "portağal", "food", "🍊", ["fruit"], ["an orange"]),
  s("bread", "çörək", "food", "🍞", ["loaf"]),
  s("water", "su", "drink", "💧", ["drink"]),
  s("milk", "süd", "drink", "🥛", ["dairy"]),
  s("coffee", "qəhvə", "drink", "☕", ["espresso"]),
  s("tea", "çay", "drink", "🍵", ["drink"]),
  s("rice", "düyü", "food", "🍚", ["grain"]),
  s("egg", "yumurta", "food", "🥚", ["food"], ["an egg"]),
  s("cheese", "pendir", "food", "🧀", ["dairy"]),
  s("chicken", "toyuq", "food", "🍗", ["meat"]),
  s("fish", "balıq", "food", "🐟", ["seafood"]),
  s("soup", "şorba", "food", "🍲", ["meal"]),
  s("salt", "duz", "food", "🧂", ["seasoning"]),
  s("sugar", "şəkər", "food", "🍬", ["sweetener"]),
  s("school", "məktəb", "education", "🏫", ["classroom"], ["a school"]),
  s("teacher", "müəllim", "people", "🧑‍🏫", ["instructor"], ["a teacher"]),
  s("student", "şagird", "people", "🎒", ["learner"], ["a student"]),
  s("book", "kitab", "object", "📘", ["textbook"], ["a book"]),
  s("pen", "qələm", "object", "🖊️", ["ballpoint"], ["a pen"]),
  s("pencil", "karandaş", "object", "✏️", ["lead pencil"], ["a pencil"]),
  s("bag", "çanta", "object", "👜", ["backpack"], ["a bag"]),
  s("phone", "telefon", "object", "📱", ["mobile"], ["a phone"]),
  s("house", "ev", "home", "🏠", ["home"], ["a house"]),
  s("room", "otaq", "home", "🚪", ["space"], ["a room"]),
  s("kitchen", "mətbəx", "home", "🍳", ["cooking room"], ["a kitchen"]),
  s("door", "qapı", "home", "🚪", ["entrance"], ["a door"]),
  s("window", "pəncərə", "home", "🪟", ["glass"], ["a window"]),
  s("table", "masa", "home", "🪑", ["desk"], ["a table"]),
  s("chair", "stul", "home", "🪑", ["seat"], ["a chair"]),
  s("bed", "çarpayı", "home", "🛏️", ["sleeping place"], ["a bed"]),
  s("car", "maşın", "transport", "🚗", ["auto"], ["a car"]),
  s("bus", "avtobus", "transport", "🚌", ["coach"], ["a bus"]),
  s("train", "qatar", "transport", "🚆", ["rail"], ["a train"]),
  s("bicycle", "velosiped", "transport", "🚲", ["bike"], ["a bicycle"]),
  s("street", "küçə", "place", "🛣️", ["road"], ["a street"]),
  s("shop", "mağaza", "place", "🏪", ["store"], ["a shop"]),
  s("market", "bazar", "place", "🛒", ["store"], ["a market"]),
  s("park", "park", "place", "🌳", ["garden"], ["a park"]),
  s("family", "ailə", "people", "👨‍👩‍👧", ["relatives"], ["a family"]),
  s("mother", "ana", "people", "👩", ["mom"], ["a mother"]),
  s("father", "ata", "people", "👨", ["dad"], ["a father"]),
  s("sister", "bacı", "people", "👧", ["sibling"], ["a sister"]),
  s("brother", "qardaş", "people", "👦", ["sibling"], ["a brother"]),
  s("friend", "dost", "people", "🤝", ["pal"], ["a friend"]),
  s("child", "uşaq", "people", "🧒", ["kid"], ["a child"]),
  s("man", "kişi", "people", "🧔", ["male"], ["a man"]),
  s("woman", "qadın", "people", "👩", ["female"], ["a woman"]),
  s("baby", "körpə", "people", "👶", ["infant"], ["a baby"]),
  s("morning", "səhər", "time", "🌅", ["early day"]),
  s("evening", "axşam", "time", "🌆", ["late day"]),
  s("night", "gecə", "time", "🌙", ["dark time"]),
  s("today", "bu gün", "time", "📅", ["this day"]),
  s("tomorrow", "sabah", "time", "➡️", ["next day"]),
  s("yesterday", "dünən", "time", "⬅️", ["previous day"]),
  s("one", "bir", "number", "1️⃣", ["number"]),
  s("two", "iki", "number", "2️⃣", ["number"]),
  s("three", "üç", "number", "3️⃣", ["number"]),
  s("ten", "on", "number", "🔟", ["number"]),
  s("red", "qırmızı", "color", "🔴", ["color"]),
  s("blue", "mavi", "color", "🔵", ["color"]),
  s("green", "yaşıl", "color", "🟢", ["color"]),
  s("black", "qara", "color", "⚫", ["color"]),
  s("white", "ağ", "color", "⚪", ["color"]),
  s("big", "böyük", "adjective", "📏", ["large"]),
  s("small", "kiçik", "adjective", "🔹", ["little"]),
  s("good", "yaxşı", "adjective", "👍", ["nice"]),
  s("bad", "pis", "adjective", "👎", ["poor"]),
  s("happy", "xoşbəxt", "feeling", "😊", ["glad"]),
  s("sad", "kədərli", "feeling", "🙁", ["unhappy"]),
  s("hot", "isti", "adjective", "🔥", ["warm"]),
  s("cold", "soyuq", "adjective", "❄️", ["cool"]),
  s("new", "yeni", "adjective", "✨", ["fresh"]),
  s("old", "köhnə", "adjective", "⌛", ["aged"]),
  s("go", "getmək", "verb", "➡️", ["move"], ["to go"]),
  s("come", "gəlmək", "verb", "⬅️", ["arrive"], ["to come"]),
  s("eat", "yemək", "verb", "🍽️", ["consume"], ["to eat"]),
  s("drink", "içmək", "verb", "🥤", ["sip"], ["to drink"]),
  s("read", "oxumaq", "verb", "📖", ["study"], ["to read"]),
  s("write", "yazmaq", "verb", "✍️", ["note"], ["to write"]),
  s("listen", "dinləmək", "verb", "🎧", ["hear"], ["to listen"]),
  s("speak", "danışmaq", "verb", "🗣️", ["talk"], ["to speak"]),
  s("see", "görmək", "verb", "👀", ["look"], ["to see"]),
  s("hear", "eşitmək", "verb", "👂", ["listen"], ["to hear"]),
  s("open", "açmaq", "verb", "🔓", ["unlock"], ["to open"]),
  s("close", "bağlamaq", "verb", "🔒", ["shut"], ["to close"]),
  s("sit", "oturmaq", "verb", "🪑", ["take a seat"], ["to sit"]),
  s("stand", "ayaqda durmaq", "verb", "🧍", ["rise"], ["to stand"]),
  s("sleep", "yatmaq", "verb", "😴", ["rest"], ["to sleep"]),
  s("work", "işləmək", "verb", "💼", ["labor"], ["to work"]),
  s("play", "oynamaq", "verb", "🎮", ["have fun"], ["to play"]),
  s("like", "xoşlamaq", "verb", "❤️", ["enjoy"], ["to like"]),
  s("want", "istəmək", "verb", "🙋", ["wish"], ["to want"]),
  s("need", "ehtiyac duymaq", "verb", "🧩", ["require"], ["to need"]),
  s("have", "sahib olmaq", "verb", "🤲", ["own"], ["to have"]),
  s("yes", "bəli", "phrase", "✅", ["correct"]),
  s("no", "xeyr", "phrase", "❌", ["negative"]),
  s("please", "zəhmət olmasa", "phrase", "🙏", ["kindly"]),
  s("hello", "salam", "phrase", "👋", ["hi"]),
  s("thank you", "təşəkkür edirəm", "phrase", "🙏", ["thanks"], ["thanks"]),
]);

const a2 = build("A2", [
  s("airport", "hava limanı", "travel", "✈️", ["terminal"], ["an airport"]),
  s("ticket", "bilet", "travel", "🎫", ["pass"], ["a ticket"]),
  s("passport", "pasport", "travel", "🛂", ["travel document"], ["a passport"]),
  s("suitcase", "çamadan", "travel", "🧳", ["luggage"], ["a suitcase"]),
  s("hotel", "otel", "travel", "🏨", ["inn"], ["a hotel"]),
  s("reservation", "rezervasiya", "travel", "📋", ["booking"], ["a reservation"]),
  s("appointment", "görüş vaxtı", "schedule", "📅", ["meeting"], ["an appointment"]),
  s("meeting", "iclas", "work", "👥", ["session"], ["a meeting"]),
  s("office", "ofis", "work", "🏢", ["workplace"], ["an office"]),
  s("manager", "menecer", "work", "🧑‍💼", ["supervisor"], ["a manager"]),
  s("colleague", "iş yoldaşı", "work", "🤝", ["coworker"], ["a colleague"]),
  s("customer", "müştəri", "work", "🛍️", ["client"], ["a customer"]),
  s("receipt", "çek", "shopping", "🧾", ["proof of purchase"], ["a receipt"]),
  s("price", "qiymət", "shopping", "🏷️", ["cost"], ["a price"]),
  s("discount", "endirim", "shopping", "💸", ["sale"], ["a discount"]),
  s("bill", "hesab", "shopping", "🧾", ["invoice"], ["a bill"]),
  s("pharmacy", "aptek", "health", "💊", ["drugstore"], ["a pharmacy"]),
  s("medicine", "dərman", "health", "💊", ["medication"]),
  s("headache", "baş ağrısı", "health", "🤕", ["pain"], ["a headache"]),
  s("fever", "qızdırma", "health", "🌡️", ["temperature"], ["a fever"]),
  s("doctor", "həkim", "health", "🩺", ["physician"], ["a doctor"]),
  s("nurse", "tibb bacısı", "health", "🏥", ["caregiver"], ["a nurse"]),
  s("hospital", "xəstəxana", "health", "🏥", ["clinic"], ["a hospital"]),
  s("exercise", "idman etmək", "health", "🏃", ["workout"]),
  s("healthy", "sağlam", "health", "🥗", ["well"]),
  s("tired", "yorğun", "feeling", "😮‍💨", ["sleepy"]),
  s("busy", "məşğul", "adjective", "📌", ["occupied"]),
  s("ready", "hazır", "adjective", "✅", ["prepared"]),
  s("early", "tez", "time", "⏰", ["before time"]),
  s("late", "gec", "time", "⌛", ["delayed"]),
  s("weather", "hava", "nature", "🌤️", ["climate"]),
  s("cloudy", "buludlu", "weather", "☁️", ["overcast"]),
  s("sunny", "günəşli", "weather", "☀️", ["bright"]),
  s("windy", "küləkli", "weather", "🌬️", ["breezy"]),
  s("rainy", "yağışlı", "weather", "🌧️", ["wet"]),
  s("temperature", "temperatur", "weather", "🌡️", ["degree"]),
  s("jacket", "gödəkçə", "clothes", "🧥", ["coat"], ["a jacket"]),
  s("shoes", "ayaqqabı", "clothes", "👟", ["footwear"]),
  s("trousers", "şalvar", "clothes", "👖", ["pants"], ["pants"]),
  s("dress", "paltar", "clothes", "👗", ["gown"], ["a dress"]),
  s("size", "ölçü", "shopping", "📐", ["measurement"], ["a size"]),
  s("color", "rəng", "shopping", "🎨", ["colour"], ["colour"]),
  s("address", "ünvan", "place", "📍", ["location"], ["an address"]),
  s("direction", "istiqamət", "place", "🧭", ["way"], ["a direction"]),
  s("corner", "künc", "place", "↩️", ["turn"], ["a corner"]),
  s("bridge", "körpü", "place", "🌉", ["crossing"], ["a bridge"]),
  s("station", "stansiya", "transport", "🚉", ["stop"], ["a station"]),
  s("platform", "platforma", "transport", "🚉", ["track"], ["a platform"]),
  s("journey", "səyahət", "travel", "🗺️", ["trip"], ["a journey"]),
  s("vacation", "tətil", "travel", "🏖️", ["holiday"], ["a vacation"]),
  s("beach", "çimərlik", "place", "🏖️", ["seaside"], ["a beach"]),
  s("mountain", "dağ", "place", "⛰️", ["hill"], ["a mountain"]),
  s("village", "kənd", "place", "🏘️", ["small town"], ["a village"]),
  s("city", "şəhər", "place", "🏙️", ["town"], ["a city"]),
  s("country", "ölkə", "place", "🌍", ["nation"], ["a country"]),
  s("language", "dil", "education", "💬", ["speech"], ["a language"]),
  s("lesson", "dərs", "education", "📚", ["class"], ["a lesson"]),
  s("homework", "ev tapşırığı", "education", "📝", ["assignment"]),
  s("exam", "imtahan", "education", "📄", ["test"], ["an exam"]),
  s("question", "sual", "education", "❓", ["query"], ["a question"]),
  s("answer", "cavab", "education", "✅", ["reply"], ["an answer"]),
  s("mistake", "səhv", "education", "⚠️", ["error"], ["a mistake"]),
  s("practice", "məşq", "education", "🎯", ["training"]),
  s("progress", "irəliləyiş", "education", "📈", ["improvement"]),
  s("send", "göndərmək", "verb", "📤", ["deliver"], ["to send"]),
  s("receive", "qəbul etmək", "verb", "📥", ["get"], ["to receive"]),
  s("borrow", "borc almaq", "verb", "🤲", ["take temporarily"], ["to borrow"]),
  s("lend", "borc vermək", "verb", "🤝", ["loan"], ["to lend"]),
  s("pay", "ödəmək", "verb", "💳", ["purchase"], ["to pay"]),
  s("cost", "qiyməti olmaq", "verb", "💰", ["be priced"], ["to cost"]),
  s("choose", "seçmək", "verb", "☑️", ["select"], ["to choose"]),
  s("decide", "qərar vermək", "verb", "🧠", ["choose"], ["to decide"]),
  s("explain", "izah etmək", "verb", "💬", ["clarify"], ["to explain"]),
  s("describe", "təsvir etmək", "verb", "🖼️", ["tell about"], ["to describe"]),
  s("invite", "dəvət etmək", "verb", "✉️", ["ask over"], ["to invite"]),
  s("visit", "ziyarət etmək", "verb", "🚪", ["go to"], ["to visit"]),
  s("wait", "gözləmək", "verb", "⏳", ["pause"], ["to wait"]),
  s("arrive", "çatmaq", "verb", "📍", ["come"], ["to arrive"]),
  s("leave", "tərk etmək", "verb", "🚪", ["depart"], ["to leave"]),
  s("return", "qayıtmaq", "verb", "↩️", ["come back"], ["to return"]),
  s("buy", "almaq", "verb", "🛒", ["purchase"], ["to buy"]),
  s("sell", "satmaq", "verb", "🏷️", ["trade"], ["to sell"]),
  s("cook", "bişirmək", "verb", "🍳", ["prepare food"], ["to cook"]),
  s("clean", "təmizləmək", "verb", "🧼", ["wash"], ["to clean"]),
  s("wash", "yumaq", "verb", "🧽", ["clean"], ["to wash"]),
  s("carry", "daşımaq", "verb", "📦", ["hold"], ["to carry"]),
  s("bring", "gətirmək", "verb", "🎁", ["take along"], ["to bring"]),
  s("take", "götürmək", "verb", "🤏", ["pick up"], ["to take"]),
  s("find", "tapmaq", "verb", "🔎", ["discover"], ["to find"]),
  s("lose", "itirmək", "verb", "❌", ["misplace"], ["to lose"]),
  s("remember", "xatırlamaq", "verb", "🧠", ["recall"], ["to remember"]),
  s("forget", "unutmaq", "verb", "💭", ["not remember"], ["to forget"]),
  s("believe", "inanmaq", "verb", "✨", ["trust"], ["to believe"]),
  s("hope", "ümid etmək", "verb", "🌈", ["wish"], ["to hope"]),
  s("agree", "razılaşmaq", "verb", "👍", ["accept"], ["to agree"]),
  s("disagree", "razılaşmamaq", "verb", "👎", ["object"], ["to disagree"]),
  s("because", "çünki", "connector", "🔗", ["since"]),
  s("before", "əvvəl", "time", "⬅️", ["earlier"]),
  s("after", "sonra", "time", "➡️", ["later"]),
  s("during", "ərzində", "time", "⏱️", ["while"]),
  s("often", "tez-tez", "frequency", "🔁", ["frequently"]),
]);

const b1 = build("B1", [
  s("achievement", "nailiyyət", "abstract", "🏆", ["success"], ["an achievement"]),
  s("advantage", "üstünlük", "abstract", "📈", ["benefit"], ["an advantage"]),
  s("advice", "məsləhət", "communication", "💡", ["guidance"]),
  s("agreement", "razılaşma", "communication", "🤝", ["deal"], ["an agreement"]),
  s("aim", "məqsəd", "abstract", "🎯", ["goal"], ["an aim"]),
  s("attitude", "münasibət", "abstract", "🧭", ["mindset"], ["an attitude"]),
  s("behavior", "davranış", "people", "🧍", ["conduct"]),
  s("belief", "inam", "abstract", "✨", ["faith"], ["a belief"]),
  s("challenge", "çətinlik", "abstract", "🧗", ["difficulty"], ["a challenge"]),
  s("choice", "seçim", "abstract", "☑️", ["option"], ["a choice"]),
  s("community", "icma", "people", "🏘️", ["society"], ["a community"]),
  s("comparison", "müqayisə", "thinking", "⚖️", ["contrast"], ["a comparison"]),
  s("confidence", "özünəinam", "feeling", "💪", ["self-belief"]),
  s("consequence", "nəticə", "abstract", "➡️", ["result"], ["a consequence"]),
  s("decision", "qərar", "thinking", "🧠", ["choice"], ["a decision"]),
  s("development", "inkişaf", "abstract", "🌱", ["growth"]),
  s("difference", "fərq", "thinking", "🔀", ["contrast"], ["a difference"]),
  s("effort", "səy", "abstract", "🏋️", ["attempt"], ["an effort"]),
  s("environment", "mühit", "nature", "🌿", ["surroundings"], ["an environment"]),
  s("experience", "təcrübə", "life", "🧳", ["practice"], ["an experience"]),
  s("explanation", "izah", "communication", "💬", ["clarification"], ["an explanation"]),
  s("failure", "uğursuzluq", "abstract", "📉", ["defeat"], ["a failure"]),
  s("feature", "xüsusiyyət", "technology", "⚙️", ["characteristic"], ["a feature"]),
  s("goal", "hədəf", "abstract", "🥅", ["aim"], ["a goal"]),
  s("habit", "vərdiş", "life", "🔁", ["routine"], ["a habit"]),
  s("improvement", "yaxşılaşma", "abstract", "📊", ["progress"], ["an improvement"]),
  s("influence", "təsir", "abstract", "🌀", ["effect"], ["an influence"]),
  s("knowledge", "bilik", "education", "🧠", ["understanding"]),
  s("opportunity", "fürsət", "abstract", "🚪", ["chance"], ["an opportunity"]),
  s("opinion", "fikir", "communication", "💭", ["view"], ["an opinion"]),
  s("permission", "icazə", "communication", "✅", ["approval"]),
  s("possibility", "ehtimal", "abstract", "🔮", ["chance"], ["a possibility"]),
  s("pressure", "təzyiq", "feeling", "🧱", ["stress"]),
  s("priority", "prioritet", "planning", "⭐", ["main concern"], ["a priority"]),
  s("reason", "səbəb", "thinking", "❔", ["cause"], ["a reason"]),
  s("relationship", "münasibət", "people", "🤝", ["connection"], ["a relationship"]),
  s("responsibility", "məsuliyyət", "work", "🧾", ["duty"]),
  s("result", "nəticə", "abstract", "📌", ["outcome"], ["a result"]),
  s("risk", "risk", "planning", "⚠️", ["danger"], ["a risk"]),
  s("solution", "həll yolu", "thinking", "🧩", ["answer"], ["a solution"]),
  s("success", "uğur", "abstract", "🏅", ["achievement"]),
  s("support", "dəstək", "people", "🤲", ["help"]),
  s("value", "dəyər", "abstract", "💎", ["worth"], ["a value"]),
  s("waste", "israf", "environment", "🗑️", ["trash"]),
  s("ability", "bacarıq", "people", "🛠️", ["skill"], ["an ability"]),
  s("accurate", "dəqiq", "adjective", "🎯", ["correct"]),
  s("aware", "xəbərdar", "adjective", "👀", ["conscious"]),
  s("common", "ümumi", "adjective", "👥", ["usual"]),
  s("complex", "mürəkkəb", "adjective", "🧬", ["complicated"]),
  s("creative", "yaradıcı", "adjective", "🎨", ["imaginative"]),
  s("effective", "səmərəli", "adjective", "✅", ["efficient"]),
  s("fair", "ədalətli", "adjective", "⚖️", ["just"]),
  s("familiar", "tanış", "adjective", "👋", ["known"]),
  s("flexible", "çevik", "adjective", "🤸", ["adaptable"]),
  s("honest", "dürüst", "adjective", "🪞", ["truthful"]),
  s("independent", "müstəqil", "adjective", "🕊️", ["self-reliant"]),
  s("local", "yerli", "adjective", "📍", ["nearby"]),
  s("personal", "şəxsi", "adjective", "🙋", ["private"]),
  s("public", "ictimai", "adjective", "🏛️", ["open"]),
  s("serious", "ciddi", "adjective", "📌", ["important"]),
  s("similar", "oxşar", "adjective", "🔁", ["alike"]),
  s("successful", "uğurlu", "adjective", "🏆", ["effective"]),
  s("useful", "faydalı", "adjective", "🧰", ["helpful"]),
  s("argue", "mübahisə etmək", "verb", "🗯️", ["debate"], ["to argue"]),
  s("avoid", "qaçınmaq", "verb", "🚧", ["stay away"], ["to avoid"]),
  s("compare", "müqayisə etmək", "verb", "⚖️", ["contrast"], ["to compare"]),
  s("complain", "şikayət etmək", "verb", "🗣️", ["protest"], ["to complain"]),
  s("consider", "nəzərə almaq", "verb", "🤔", ["think about"], ["to consider"]),
  s("continue", "davam etmək", "verb", "➡️", ["keep going"], ["to continue"]),
  s("create", "yaratmaq", "verb", "🛠️", ["make"], ["to create"]),
  s("depend", "asılı olmaq", "verb", "🔗", ["rely"], ["to depend"]),
  s("develop", "inkişaf etdirmək", "verb", "🌱", ["grow"], ["to develop"]),
  s("encourage", "həvəsləndirmək", "verb", "👏", ["motivate"], ["to encourage"]),
  s("include", "daxil etmək", "verb", "➕", ["contain"], ["to include"]),
  s("increase", "artırmaq", "verb", "📈", ["raise"], ["to increase"]),
  s("introduce", "tanıtmaq", "verb", "👋", ["present"], ["to introduce"]),
  s("manage", "idarə etmək", "verb", "🧑‍💼", ["control"], ["to manage"]),
  s("organize", "təşkil etmək", "verb", "🗂️", ["arrange"], ["to organize"]),
  s("prepare", "hazırlamaq", "verb", "🧑‍🍳", ["get ready"], ["to prepare"]),
  s("protect", "qorumaq", "verb", "🛡️", ["defend"], ["to protect"]),
  s("realize", "başa düşmək", "verb", "💡", ["understand"], ["to realize"]),
  s("reduce", "azaltmaq", "verb", "📉", ["decrease"], ["to reduce"]),
  s("refuse", "imtina etmək", "verb", "🚫", ["reject"], ["to refuse"]),
  s("suggest", "təklif etmək", "verb", "💬", ["recommend"], ["to suggest"]),
  s("suppose", "güman etmək", "verb", "🤔", ["assume"], ["to suppose"]),
  s("achieve", "nail olmaq", "verb", "🏁", ["reach"], ["to achieve"]),
  s("affect", "təsir etmək", "verb", "🌀", ["influence"], ["to affect"]),
  s("allow", "icazə vermək", "verb", "✅", ["permit"], ["to allow"]),
  s("apply", "müraciət etmək", "verb", "📄", ["request"], ["to apply"]),
  s("attend", "iştirak etmək", "verb", "🎟️", ["go to"], ["to attend"]),
  s("cancel", "ləğv etmək", "verb", "❌", ["call off"], ["to cancel"]),
  s("confirm", "təsdiqləmək", "verb", "☑️", ["verify"], ["to confirm"]),
  s("connect", "birləşdirmək", "verb", "🔌", ["link"], ["to connect"]),
  s("deliver", "çatdırmaq", "verb", "📦", ["bring"], ["to deliver"]),
  s("discover", "kəşf etmək", "verb", "🔎", ["find"], ["to discover"]),
  s("discuss", "müzakirə etmək", "verb", "💬", ["talk about"], ["to discuss"]),
  s("identify", "müəyyən etmək", "verb", "🪪", ["recognize"], ["to identify"]),
  s("maintain", "saxlamaq", "verb", "🧰", ["keep"], ["to maintain"]),
  s("negotiate", "danışıqlar aparmaq", "verb", "🤝", ["bargain"], ["to negotiate"]),
  s("participate", "iştirak etmək", "verb", "🙋", ["take part"], ["to participate"]),
  s("respond", "cavab vermək", "verb", "💬", ["reply"], ["to respond"]),
]);

const outputDir = path.join(process.cwd(), "src", "data", "words");
mkdirSync(outputDir, { recursive: true });

const files: Record<string, WordItem[]> = {
  "a1.json": a1,
  "a2.json": a2,
  "b1.json": b1,
};

for (const [fileName, words] of Object.entries(files)) {
  writeFileSync(path.join(outputDir, fileName), `${JSON.stringify(words, null, 2)}\n`, "utf8");
}

console.log(
  `Generated ${a1.length} A1, ${a2.length} A2, and ${b1.length} B1 sample words. Prefer buildWordBank.ts for B2 and expansions.`,
);
